# Generated by Django 3.1.2 on 2020-11-28 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Passport',
            fields=[
                ('id', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('area', models.IntegerField()),
                ('birthdate', models.CharField(max_length=13)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
